---
title: "ggcal"
output: 
  html_document:
    theme: null
    highlight: null
    mathjax: null
    self_contained: false
---
```{r setup, include=FALSE}
devtools::install_github("jayjacobs/ggcal")
```


```{r , include=FALSE}
library(ggplot2)
library(ggcal)
library(dplyr)
library(forcats)
library(tibble)

mydate <- seq(as.Date("2020-06-01"), as.Date("2020-06-30"), by="1 day")
myfills <- ifelse(format(mydate, "%w") %in% c(0,6), "weekend" ,"weekday")

June_cal <- ggcal(mydate, myfills)+
  scale_fill_manual(values=c("weekday"="white", "weekend"="#BBF5D0"))

print(June_cal)
```


```{r , include=FALSE}
ggcal <- function(dates, fills) {
  # get ordered vector of month names
  months <- format(seq(as.Date("2016-01-01"), as.Date("2016-12-01"), by="1 month"), "%B")

  # get lower and upper bound to fill in missing values
  mindate <- as.Date(format(min(mydate), "%Y-%m-01"))
  maxdate <- (seq(as.Date(format(max(mydate), "%Y-%m-01")), length.out = 2, by="1 month")-1)[2]
  # set up tibble with all the dates.
  filler <- tibble(date = seq(mindate, maxdate, by="1 day"))

  t1 <- tibble(date = mydate, fill=myfills) %>%
    right_join(filler, by="date") %>% # fill in missing dates with NA
    mutate(dow = as.numeric(format(date, "%w"))) %>%
    mutate(month = format(date, "%B")) %>%
    mutate(day = as.numeric(format(date,"%d"))) %>%
    mutate(woy = as.numeric(format(date, "%U"))) %>%
    mutate(year = as.numeric(format(date, "%Y"))) %>%
    mutate(month = factor(month, levels=months, ordered=TRUE)) %>%
    arrange(year, month) %>%
    mutate(monlabel=month)
  
  print(t1)

  if (length(unique(t1$year))>1) { # multi-year data set
    t1$monlabel <- paste(t1$month, t1$year)
  }

  t2 <- t1 %>%
    mutate(monlabel = factor(monlabel, ordered=TRUE)) %>%
    mutate(monlabel = fct_inorder(monlabel)) %>%
    mutate(monthweek = woy-min(woy),
           y=max(monthweek)-monthweek+1)
  
  print(t2)

weekdays <- c("日", "一", "二", "三", "四", "五", "六")
ggplot(t2, aes(dow, y, fill=fill)) +
  geom_tile(color="dimgray") +
  geom_text(aes(label = day),nudge_x = -0.35,nudge_y = 0.2)+
  facet_wrap(~monlabel, ncol=3, scales="free") +
  scale_x_continuous(expand=c(0,0), position="top",
                     breaks=seq(0,6), labels=weekdays) +
  scale_y_continuous(expand=c(0,0)) +
  theme(panel.background=element_rect(fill=NA, color=NA),
        strip.background = element_rect(fill=NA, color=NA),
        strip.text.x = element_blank(),
        legend.title = element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank(),
        axis.text.y = element_blank(),
        strip.placement = "outsite",
        legend.position = "none")
}

```


```{r , include=FALSE}
June_cal
gridSVG::grid.export("June_cal.svg",addClasses=TRUE)
```

